// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIH8ZFipLUn7-1ipvuybsw9aEfdUJDv0o',
    appId: '1:567338136072:web:fb270ca542eaca719417bd',
    messagingSenderId: '567338136072',
    projectId: 'hathariapp',
    authDomain: 'hathariapp.firebaseapp.com',
    storageBucket: 'hathariapp.firebasestorage.app',
    measurementId: 'G-CNLVM0DVTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_GBodz9vjIVyW1d-BdM3rTdb3r4LVwUE',
    appId: '1:567338136072:android:b4235873c2cdf5f39417bd',
    messagingSenderId: '567338136072',
    projectId: 'hathariapp',
    storageBucket: 'hathariapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJlj1hB4xOY4qfNn-WAbDM76kBMFePyvc',
    appId: '1:567338136072:ios:529a51ce6637f2a89417bd',
    messagingSenderId: '567338136072',
    projectId: 'hathariapp',
    storageBucket: 'hathariapp.firebasestorage.app',
    iosBundleId: 'com.example.hathariApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJlj1hB4xOY4qfNn-WAbDM76kBMFePyvc',
    appId: '1:567338136072:ios:529a51ce6637f2a89417bd',
    messagingSenderId: '567338136072',
    projectId: 'hathariapp',
    storageBucket: 'hathariapp.firebasestorage.app',
    iosBundleId: 'com.example.hathariApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIH8ZFipLUn7-1ipvuybsw9aEfdUJDv0o',
    appId: '1:567338136072:web:b956ed8fdd15bef59417bd',
    messagingSenderId: '567338136072',
    projectId: 'hathariapp',
    authDomain: 'hathariapp.firebaseapp.com',
    storageBucket: 'hathariapp.firebasestorage.app',
    measurementId: 'G-GV7985FLS6',
  );
}
